// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const claimOutbox = `-- name: ClaimOutbox :one
WITH candidate AS (SELECT e.sequence FROM outbox e
 WHERE e.destination=$3 AND e.published_at=0 AND e.next_attempt_at<=CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT) AND e.claim_expires_at<=CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT)
 AND (e.ordering_key='' OR NOT EXISTS (SELECT 1 FROM outbox prior
  WHERE prior.tenant_id=e.tenant_id AND prior.destination=e.destination AND prior.ordering_key=e.ordering_key
  AND prior.published_at=0 AND prior.sequence<e.sequence))
 ORDER BY e.sequence LIMIT 1 FOR UPDATE OF e SKIP LOCKED)
UPDATE outbox o SET claim_token=$1,claim_expires_at=CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT)+CAST($2 AS BIGINT),attempt_count=o.attempt_count+1
FROM candidate c WHERE o.sequence=c.sequence
RETURNING o.tenant_id,o.id,o.destination,o.ordering_key,o.kind,o.payload_version,o.payload,o.created_at,o.claim_token,o.attempt_count
`

type ClaimOutboxParams struct {
	ClaimToken  string
	TtlMs       int64
	Destination string
}

type ClaimOutboxRow struct {
	TenantID       string
	ID             string
	Destination    string
	OrderingKey    string
	Kind           string
	PayloadVersion int64
	Payload        []byte
	CreatedAt      int64
	ClaimToken     string
	AttemptCount   int64
}

func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) (*ClaimOutboxRow, error) {
	row := q.db.QueryRow(ctx, claimOutbox, arg.ClaimToken, arg.TtlMs, arg.Destination)
	var i ClaimOutboxRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Destination,
		&i.OrderingKey,
		&i.Kind,
		&i.PayloadVersion,
		&i.Payload,
		&i.CreatedAt,
		&i.ClaimToken,
		&i.AttemptCount,
	)
	return &i, err
}

const completeOutbox = `-- name: CompleteOutbox :execrows
UPDATE outbox SET published_at=CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT),claim_token='',claim_expires_at=0,last_error_code=''
WHERE tenant_id=$1 AND id=$2 AND claim_token=$3
AND published_at=0 AND claim_expires_at>CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT)
`

type CompleteOutboxParams struct {
	TenantID   string
	ID         string
	ClaimToken string
}

func (q *Queries) CompleteOutbox(ctx context.Context, arg CompleteOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOutbox, arg.TenantID, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox(tenant_id,id,destination,ordering_key,kind,payload_version,payload,created_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(tenant_id,id) DO UPDATE SET id=excluded.id
WHERE outbox.destination=excluded.destination AND outbox.ordering_key=excluded.ordering_key AND outbox.kind=excluded.kind
AND outbox.payload_version=excluded.payload_version AND outbox.payload=excluded.payload AND outbox.created_at=excluded.created_at
RETURNING id
`

type InsertOutboxParams struct {
	TenantID       string
	ID             string
	Destination    string
	OrderingKey    string
	Kind           string
	PayloadVersion int64
	Payload        []byte
	CreatedAt      int64
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (string, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.TenantID,
		arg.ID,
		arg.Destination,
		arg.OrderingKey,
		arg.Kind,
		arg.PayloadVersion,
		arg.Payload,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockOutboxTenant = `-- name: LockOutboxTenant :one
SELECT id FROM tenants WHERE id=$1 FOR NO KEY UPDATE
`

func (q *Queries) LockOutboxTenant(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, lockOutboxTenant, tenantID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const retryOutbox = `-- name: RetryOutbox :execrows
UPDATE outbox SET next_attempt_at=CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT)+CAST($1 AS BIGINT),last_error_code=$2,claim_token='',claim_expires_at=0
WHERE tenant_id=$3 AND id=$4 AND claim_token=$5
AND published_at=0 AND claim_expires_at>CAST(extract(epoch FROM clock_timestamp()) * 1000 AS BIGINT)
`

type RetryOutboxParams struct {
	DelayMs    int64
	ErrorCode  string
	TenantID   string
	ID         string
	ClaimToken string
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutbox,
		arg.DelayMs,
		arg.ErrorCode,
		arg.TenantID,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
